project_name: sonar

builds:
  - dir: sonar
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/felicianotech/sonar/sonar/cmd.version={{ .Version }} -extldflags "-static"

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md
    replacements:
      darwin: macos

nfpms:
  - file_name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    homepage: "https://www.Feliciano.Tech"
    maintainer: "Ricardo N Feliciano <Ricardo@Feliciano.Tech>"
    description: "A Docker utility."
    license: MIT
    formats:
      - deb
    bindir: /usr/bin

brews:
  - tap:
      owner: felicianotech
      name: homebrew-tap
    commit_author:
      name: "Ricardo N Feliciano (FelicianoTech)"
      email: "Ricardo@Feliciano.Tech"
    folder: Formula
    homepage: "https://github.com/felicianotech/sonar"
    description: "A Docker utility."
    test: |
      system "#{bin}/sonar", "help"

checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-checksums.txt"
