name: sonar
title: "Sonar"
summary: "A Docker utility."
description: |
  Sonar is a Docker utility that allows you to display information on Docker images, tags, and layers as well as Docker Hub metrics.
license: MIT
base: core18
grade: stable
confinement: strict
adopt-info: sonar

parts:
  sonar:
    plugin: dump
    source: .
    override-build: |
      snapcraftctl build

      cp dist/sonar_linux_amd64/sonar $SNAPCRAFT_PART_INSTALL

      chmod +x $SNAPCRAFT_PART_INSTALL/sonar

      snapcraftctl set-version $(cat VERSION)

apps:
  sonar:
    command: sonar
    plugs:
      - home
      - network
