name: sonar
title: "Sonar"
summary: "The missing Docker & Docker Hub utility. Quickly query image information."
description: |
  Sonar is the Docker and Docker Hub utility that you've been missing. It can
  display information on Docker images, tags, and layers including the packages
  installed in those images.

  Docker Hub metrics such as stars and pulls can be read while tasks such as
  updating the readme, summary, or even deleting tags from Docker Hub can be
  done with Sonar.

  The source code can be found on GitHub: https://github.com/felicianotech/sonar
license: MIT
base: core18
grade: stable
confinement: strict
icon: img/icon-x512.png
adopt-info: sonar

parts:
  sonar:
    plugin: dump
    source: .
    override-build: |
      snapcraftctl build

      # Choose binary based on architecture
      case $SNAPCRAFT_ARCH_TRIPLET in
        # Linux amd64
        x86_64-linux-gnu)
          cp dist/sonar_linux_amd64/sonar $SNAPCRAFT_PART_INSTALL
          ;;
        # Linux armhf -> armv7 -> Raspberry Pi 2 B+ and newer/32bit OSs
        arm-linux-gnueabihf)
          cp dist/sonar_linux_arm_7/sonar $SNAPCRAFT_PART_INSTALL
          ;;
        # Linux arm64 -> armv8 -> Raspberry Pi 3 B+ and newer/64bit OSs
        aarch64-linux-gnu)
          cp dist/sonar_linux_arm_7/sonar $SNAPCRAFT_PART_INSTALL
          ;;
        *)
          echo "Error: Unsupported architecture!"
          exit 1
      esac

      chmod +x $SNAPCRAFT_PART_INSTALL/sonar
      snapcraftctl set-version $(cat VERSION)

apps:
  sonar:
    command: sonar
    plugs:
      - home
      - network
